version: "3.9"

networks:
  devlog-network:
    driver: bridge

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - devlog-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/actuator/health"]
      start_period: 60s
      interval: 60s
      timeout: 5s
      retries: 5
    environment:
      DEVLOG_TEST_DB_HOST: ${DEVLOG_TEST_DB_HOST}
      DEVLOG_TEST_DB_NM: ${DEVLOG_TEST_DB_NM}
      DEVLOG_TEST_DB_PW: ${DEVLOG_TEST_DB_PW}
      DEVLOG_GOOGLE_CLIENT_ID: ${DEVLOG_GOOGLE_CLIENT_ID}
      DEVLOG_GOOGLE_CLIENT_SECRET: ${DEVLOG_GOOGLE_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      RECAPTCHA_PRIVATE_KEY: ${RECAPTCHA_PRIVATE_KEY}
      DEVLOG_MAIL_USERNAME: ${DEVLOG_MAIL_USERNAME}
      DEVLOG_MAIL_PASSWORD: ${DEVLOG_MAIL_PASSWORD}
    volumes:
      - /home/app/static/resource:/home/static/resource
      - /home/app/sitemap:/app/sitemap
      - /home/app/sub-sitemap:/app/sub-sitemap

  redis:
    image: redis:7.4
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - devlog-network

  # database:
  #   image: mysql:8.0
  #   restart: on-failure
  #   environment:
  #     MYSQL_DATABASE: devlog
  #     MYSQL_ROOT_HOST: "%"
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
  #   ports:
  #     - "3306:3306"
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   tty: true
  #   networks:
  #     - devlog-network
