networks:
  devlog-network:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - devlog-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      DEVLOG_MAIN_DB_HOST: ${DEVLOG_MAIN_DB_HOST}
      DEVLOG_MAIN_DB_NM: ${DEVLOG_MAIN_DB_NM}
      DEVLOG_MAIN_DB_PW: ${DEVLOG_MAIN_DB_PW}
      DEVLOG_GOOGLE_CLIENT_ID: ${DEVLOG_GOOGLE_CLIENT_ID}
      DEVLOG_GOOGLE_CLIENT_SECRET: ${DEVLOG_GOOGLE_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      RECAPTCHA_PRIVATE_KEY: ${RECAPTCHA_PRIVATE_KEY}
      DEVLOG_MAIL_USERNAME: ${DEVLOG_MAIL_USERNAME}
      DEVLOG_MAIL_PASSWORD: ${DEVLOG_MAIL_PASSWORD}
    volumes:
      - /home/static/resource:/home/static/resource
      - /home/app/frontend/sitemap:/app/sitemap
      - /home/app/backend/sub-sitemap:/app/sub-sitemap
    restart: on-failure

  redis:
    image: redis:7.4
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - devlog-network
    restart: on-failure
