FROM python:3.11-slim

ENV POETRY_VERSION=1.8.3
ENV PYTHON_VERSION=3.11

RUN apt-get update && apt-get install -y tzdata

RUN ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime

RUN pip install poetry==$POETRY_VERSION

ENV PATH="/root/.local/bin:$PATH"