FROM gradle:8.14.3-jdk17

WORKDIR /app

RUN apt-get update && apt-get install -y tzdata

# 타임존 설정
ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY ./main-service.jar .

ENTRYPOINT ["java", "-jar", "main-service.jar", "--spring.profiles.active=prod"]